"""
agents/v2/test_writer_v2.py
M5: Porting the TestWriter to the V2 Reflexion architecture.
"""
import os
from pathlib import Path
from srp.agents.v2.reflexion_agent import ReflexionAgent

class TestWriterV2(ReflexionAgent):
    """
    V2 TestWriter utilizing the OODA Reflexion loop.
    Generates Foundry tests, attempts compiling them, and self-corrects on failure.
    """
    def __init__(self, run_id: str = None):
        super().__init__(run_id=run_id, max_retries=3)
        self.model = "claude-sonnet-4-6"

    async def write_to_disk_hook(self, text: str, project_root: str):
        """Hook called by the Evaluator node before running Foundry constraint tests."""
        # For evaluation, we write the generated test file into the project /test/ folder
        test_dir = Path(project_root) / "test"
        if not test_dir.exists():
            test_dir.mkdir(parents=True)
            
        test_path = test_dir / "SRP_AutoGeneratedTest.t.sol"
        with open(test_path, "w") as f:
            f.write(text)

    async def run(self, context: dict) -> dict:
        code = context.get("code", "")
        if not code:
            return {"tests": "", "error": "No code provided"}

        # Use the base graph execution
        initial_state = {
            "task": "Generate a comprehensive Foundry test file for the provided Solidity contract. Include setUp(), happy path, revert tests, and fuzz tests. Must compile.",
            "code": code,
            "project_root": context.get("project_root", "."),
            "eval_tool": "foundry",
            "eval_args": {"action": "build"},
            "write_hook": self.write_to_disk_hook,
            "retries": 0,
            "is_successful": False
        }
        
        final_state = await super().run(initial_state)
        
        return {
            "tests": final_state.get("current_output", ""),
            "is_verified": final_state.get("is_successful", False),
            "retries_taken": final_state.get("retries", 1),
            "episodic_memory": self.memory.get_recent_episodes()
        }
