export interface Lesson {
  id: string;
  title: string;
  description: string;
  xpReward: number;
  duration: number;
  chain: "ethereum" | "solana" | "both";
  tags: string[];
  content: string;
  quiz: { question: string; options: string[]; correct: number }[];
}

export interface LearningPath {
  id: string;
  title: string;
  description: string;
  chain: "ethereum" | "solana" | "both";
  level: "beginner" | "intermediate" | "advanced";
  lessons: Lesson[];
  totalXP: number;
  color: string;
  icon: string;
}

export const LEARNING_PATHS: LearningPath[] = [
  {
    id: "eth-foundations",
    title: "Ethereum Foundations",
    description: "From zero to deploying your first smart contract",
    chain: "ethereum",
    level: "beginner",
    totalXP: 1500,
    color: "from-indigo-500 to-purple-600",
    icon: "⟠",
    lessons: [
      {
        id: "eth-001",
        title: "What is Ethereum?",
        description: "The world computer explained simply",
        xpReward: 100,
        duration: 8,
        chain: "ethereum",
        tags: ["basics", "blockchain"],
        content: `Ethereum is a decentralized, open-source blockchain with smart contract functionality. Think of it as a programmable blockchain — not just a ledger of transactions, but a computer anyone can use without permission.

**Key concepts:**
- **Blockchain**: A chain of blocks, each containing transactions, secured by cryptography
- **Decentralization**: No single company or government controls it — thousands of computers worldwide run it
- **Ether (ETH)**: The native currency used to pay for computation
- **Smart Contracts**: Programs that live on the blockchain and execute automatically when conditions are met

**Why it matters:**
Ethereum enables trustless applications — you don't need to trust a company or government. The code is the law. This unlocks entirely new possibilities: decentralized finance, NFTs, DAOs, and much more.

**The EVM:**
The Ethereum Virtual Machine (EVM) is the runtime environment for smart contracts. It's a sandboxed virtual stack machine embedded within each Ethereum node — identical behavior across all nodes guarantees determinism.`,
        quiz: [
          {
            question: "What makes Ethereum different from Bitcoin?",
            options: [
              "Ethereum is faster",
              "Ethereum supports smart contracts and programmable logic",
              "Ethereum is more decentralized",
              "Ethereum has lower fees"
            ],
            correct: 1
          },
          {
            question: "What is the EVM?",
            options: [
              "Ethereum Value Machine",
              "A type of wallet",
              "The runtime environment that executes smart contracts",
              "A consensus algorithm"
            ],
            correct: 2
          }
        ]
      },
      {
        id: "eth-002",
        title: "Wallets & Accounts",
        description: "Your identity on-chain — keys, addresses, and signing",
        xpReward: 120,
        duration: 10,
        chain: "ethereum",
        tags: ["wallets", "accounts", "keys"],
        content: `In Ethereum, your identity is a cryptographic key pair — not a username and password.

**Two types of accounts:**
1. **Externally Owned Accounts (EOA)**: Controlled by private keys — this is your wallet. No code, just balance + nonce.
2. **Contract Accounts**: Controlled by code (smart contracts). They have balance + storage + code.

**Key pair basics:**
- **Private Key**: 256 bits of randomness. This is everything — whoever has it, owns the account. NEVER share it.
- **Public Key**: Derived mathematically from your private key via elliptic curve cryptography (secp256k1).
- **Address**: The last 20 bytes of the Keccak-256 hash of your public key. This is what you share.

**How transactions work:**
1. You create a transaction (to, value, data, gas)
2. You sign it with your private key — this creates a cryptographic signature
3. Anyone can verify the signature using your public key
4. The network broadcasts and includes it in a block

**Popular wallets:**
- MetaMask (browser extension / mobile)
- Ledger / Trezor (hardware — most secure)
- Rainbow, Coinbase Wallet (mobile-first)`,
        quiz: [
          {
            question: "What is an Ethereum address derived from?",
            options: [
              "Your username",
              "A random number generated by MetaMask",
              "The last 20 bytes of the Keccak-256 hash of your public key",
              "Your private key directly"
            ],
            correct: 2
          },
          {
            question: "What happens if someone gets your private key?",
            options: [
              "Nothing — they still need your password",
              "They can read your transactions",
              "They have full control of your account and all its funds",
              "They can only view your balance"
            ],
            correct: 2
          }
        ]
      },
      {
        id: "eth-003",
        title: "Gas & Transactions",
        description: "How computation is priced and transactions are ordered",
        xpReward: 130,
        duration: 12,
        chain: "ethereum",
        tags: ["gas", "transactions", "fees"],
        content: `Gas is the unit that measures computational effort in Ethereum. Every operation costs gas — this prevents infinite loops and spam.

**Gas anatomy:**
- **Gas Limit**: Max gas you're willing to use. Set too low → transaction reverts. Set too high → excess refunded.
- **Base Fee**: Protocol-determined fee per gas unit, burned (destroyed) each block. Adjusts automatically based on demand.
- **Priority Fee (Tip)**: Extra fee you pay to incentivize validators to include your transaction faster.
- **Max Fee**: The most you're willing to pay per gas unit total (base fee + tip).

**Transaction fields:**
\`\`\`
{
  nonce: 42,          // Your account's transaction count — prevents replay
  to: "0x...",        // Recipient (null for contract deployment)
  value: 1e18,        // ETH in wei (1 ETH = 10^18 wei)
  data: "0x...",      // Calldata — empty for ETH transfer, encoded for contracts
  gasLimit: 21000,    // Standard ETH transfer = 21,000 gas
  maxFeePerGas: ...,
  maxPriorityFeePerGas: ...
}
\`\`\`

**EIP-1559 (London upgrade):**
The base fee is burned, removing it from circulation. This made ETH deflationary during high-activity periods.

**Transaction lifecycle:**
1. Broadcast → Mempool (waiting room)
2. Validators pick highest-fee transactions
3. Included in block → executed
4. Finalized after multiple block confirmations`,
        quiz: [
          {
            question: "What happens to the base fee in Ethereum transactions?",
            options: [
              "It goes to the validator",
              "It is burned (destroyed)",
              "It goes to the Ethereum Foundation",
              "It is split between validators and developers"
            ],
            correct: 1
          },
          {
            question: "How much gas does a standard ETH transfer cost?",
            options: ["100 gas", "1,000 gas", "21,000 gas", "100,000 gas"],
            correct: 2
          }
        ]
      },
      {
        id: "eth-004",
        title: "Your First Solidity Contract",
        description: "Write, compile, and deploy a smart contract",
        xpReward: 200,
        duration: 20,
        chain: "ethereum",
        tags: ["solidity", "smart contracts", "deploy"],
        content: `Solidity is a statically typed, compiled language for writing smart contracts on the EVM.

**Hello World contract:**
\`\`\`solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

contract HelloWeb3 {
    string public message;
    address public owner;

    constructor(string memory _message) {
        message = _message;
        owner = msg.sender;
    }

    function setMessage(string memory _newMessage) public {
        require(msg.sender == owner, "Not the owner");
        message = _newMessage;
    }

    function getMessage() public view returns (string memory) {
        return message;
    }
}
\`\`\`

**Key concepts explained:**
- \`pragma solidity\`: Compiler version — always pin it
- \`msg.sender\`: The address calling the function
- \`public\`: Anyone can call this function (or read this variable)
- \`view\`: Doesn't modify state — free to call (no gas for reads)
- \`require\`: Reverts with an error message if condition is false
- \`constructor\`: Runs once when deployed

**Data types:**
- \`uint256\`: Unsigned 256-bit integer (most common)
- \`address\`: 20-byte Ethereum address
- \`bool\`: True/false
- \`string\`: UTF-8 text (expensive — stored in calldata or memory)
- \`bytes32\`: Fixed-size byte array (efficient for hashes)

**Tools to deploy:**
- Remix IDE (browser-based, easiest to start)
- Hardhat + ethers.js (production workflow)
- Foundry (fastest, Rust-based)`,
        quiz: [
          {
            question: "What does 'view' mean in a Solidity function?",
            options: [
              "The function is private",
              "The function reads state but doesn't modify it — no gas cost for direct calls",
              "The function can only be called by the owner",
              "The function returns a visual output"
            ],
            correct: 1
          },
          {
            question: "What is msg.sender?",
            options: [
              "The contract address",
              "The deployer's address",
              "The address of whoever called the current function",
              "The validator's address"
            ],
            correct: 2
          }
        ]
      },
      {
        id: "eth-005",
        title: "ERC-20 Tokens",
        description: "Build your own fungible token from scratch",
        xpReward: 180,
        duration: 18,
        chain: "ethereum",
        tags: ["erc20", "tokens", "standards"],
        content: `ERC-20 is the standard interface for fungible tokens on Ethereum. Every DeFi token you've heard of (USDC, LINK, UNI) implements this standard.

**The ERC-20 interface:**
\`\`\`solidity
interface IERC20 {
    function totalSupply() external view returns (uint256);
    function balanceOf(address account) external view returns (uint256);
    function transfer(address to, uint256 amount) external returns (bool);
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 amount) external returns (bool);
    function transferFrom(address from, address to, uint256 amount) external returns (bool);

    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);
}
\`\`\`

**Using OpenZeppelin (the safe way):**
\`\`\`solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

contract MyToken is ERC20, Ownable {
    constructor() ERC20("MyToken", "MTK") Ownable(msg.sender) {
        _mint(msg.sender, 1_000_000 * 10 ** decimals());
    }

    function mint(address to, uint256 amount) public onlyOwner {
        _mint(to, amount);
    }
}
\`\`\`

**The approval pattern (approve + transferFrom):**
This enables smart contracts to spend tokens on your behalf:
1. You call \`approve(contractAddress, amount)\` → gives permission
2. Contract calls \`transferFrom(you, recipient, amount)\` → moves tokens

This is how DEXes like Uniswap work.

**Common pitfalls:**
- Infinite approvals are risky — if the contract is hacked, all approved tokens can be drained
- The double-spend attack on approve() — always use increaseAllowance/decreaseAllowance`,
        quiz: [
          {
            question: "Why does ERC-20 have both 'transfer' and 'transferFrom'?",
            options: [
              "They do the same thing",
              "'transferFrom' allows smart contracts to move tokens on your behalf after you approve them",
              "'transfer' is for ETH and 'transferFrom' is for tokens",
              "'transferFrom' is cheaper in gas"
            ],
            correct: 1
          }
        ]
      }
    ]
  },
  {
    id: "sol-foundations",
    title: "Solana Foundations",
    description: "Programs, accounts, and the fastest blockchain on earth",
    chain: "solana",
    level: "beginner",
    totalXP: 1500,
    color: "from-green-500 to-teal-600",
    icon: "◎",
    lessons: [
      {
        id: "sol-001",
        title: "What is Solana?",
        description: "Speed, scale, and the Proof of History innovation",
        xpReward: 100,
        duration: 8,
        chain: "solana",
        tags: ["basics", "blockchain", "poh"],
        content: `Solana is a high-performance blockchain built for speed and scale. While Ethereum processes ~15 transactions per second, Solana handles 65,000+ TPS with sub-second finality.

**How Solana achieves speed:**

**1. Proof of History (PoH):**
A verifiable delay function that creates a historical record proving events happened at a specific time. Think of it as a cryptographic timestamp. Validators don't need to communicate to agree on time — they can verify the sequence independently.

**2. Tower BFT:**
A PoH-optimized version of Practical Byzantine Fault Tolerance (PBFT). Validators vote on the state of the ledger using PoH as a clock.

**3. Turbine:**
A block propagation protocol that breaks data into small packets and transmits them to validators — inspired by BitTorrent.

**4. Gulf Stream:**
Mempool-less transaction forwarding. Validators already know which transactions are coming before the current block is even finished.

**5. Sealevel:**
Parallel smart contract runtime. Unlike Ethereum's sequential EVM, Sealevel can process thousands of contracts in parallel (when they don't touch the same state).

**SOL token:**
Used for transaction fees (~0.000005 SOL), staking, and rent for on-chain storage.`,
        quiz: [
          {
            question: "What is Proof of History?",
            options: [
              "A mining algorithm like Bitcoin",
              "A verifiable delay function that creates a trusted record of time between events",
              "A way to prove token ownership history",
              "Solana's staking mechanism"
            ],
            correct: 1
          }
        ]
      },
      {
        id: "sol-002",
        title: "Accounts & Programs",
        description: "Solana's unique account model — everything is an account",
        xpReward: 130,
        duration: 12,
        chain: "solana",
        tags: ["accounts", "programs", "model"],
        content: `Solana's account model is fundamentally different from Ethereum. Understanding this is the key to writing Solana programs.

**Everything is an account:**
- Wallets are accounts
- Programs (smart contracts) are accounts
- Program data is stored in separate accounts
- Tokens are accounts
- Even the clock is an account (sysvar)

**Account structure:**
\`\`\`
Account {
  key: Pubkey,          // Address (32 bytes)
  lamports: u64,        // SOL balance (1 SOL = 10^9 lamports)
  data: Vec<u8>,        // Arbitrary data
  owner: Pubkey,        // Which program owns this account
  executable: bool,     // Is this a program?
  rent_epoch: u64       // Rent-related (being deprecated)
}
\`\`\`

**Key difference from Ethereum:**
In Ethereum, contracts store their own state. In Solana, programs are stateless — they only contain code. All state lives in separate data accounts that the program owns.

**Program Derived Addresses (PDAs):**
Deterministic addresses derived from seeds + program ID. No private key — only the program can sign for them.
\`\`\`rust
let (pda, bump) = Pubkey::find_program_address(
    &[b"vault", user.key().as_ref()],
    &program_id
);
\`\`\`

**Rent:**
Accounts must maintain a minimum balance to stay alive (~0.002 SOL for small accounts). Being "rent-exempt" means your balance covers storage indefinitely.`,
        quiz: [
          {
            question: "Where does a Solana program store its state?",
            options: [
              "Inside the program account itself",
              "In separate data accounts that the program owns",
              "In a global state variable",
              "On IPFS"
            ],
            correct: 1
          }
        ]
      },
      {
        id: "sol-003",
        title: "Anchor Framework",
        description: "The safe, ergonomic way to write Solana programs",
        xpReward: 200,
        duration: 20,
        chain: "solana",
        tags: ["anchor", "rust", "programs"],
        content: `Anchor is to Solana what OpenZeppelin + Hardhat is to Ethereum. It makes writing Solana programs dramatically safer and faster.

**Your first Anchor program:**
\`\`\`rust
use anchor_lang::prelude::*;

declare_id!("YourProgramIDHere...");

#[program]
pub mod counter {
    use super::*;

    pub fn initialize(ctx: Context<Initialize>, start: u64) -> Result<()> {
        let counter = &mut ctx.accounts.counter;
        counter.count = start;
        counter.authority = ctx.accounts.user.key();
        Ok(())
    }

    pub fn increment(ctx: Context<Increment>) -> Result<()> {
        let counter = &mut ctx.accounts.counter;
        require!(
            ctx.accounts.user.key() == counter.authority,
            ErrorCode::Unauthorized
        );
        counter.count += 1;
        Ok(())
    }
}

#[derive(Accounts)]
pub struct Initialize<'info> {
    #[account(
        init,
        payer = user,
        space = 8 + Counter::INIT_SPACE
    )]
    pub counter: Account<'info, Counter>,
    #[account(mut)]
    pub user: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct Increment<'info> {
    #[account(mut)]
    pub counter: Account<'info, Counter>,
    pub user: Signer<'info>,
}

#[account]
#[derive(InitSpace)]
pub struct Counter {
    pub count: u64,
    pub authority: Pubkey,
}

#[error_code]
pub enum ErrorCode {
    #[msg("You are not the authority")]
    Unauthorized,
}
\`\`\`

**What Anchor handles for you:**
- Account discriminator (8-byte tag identifying account types)
- Deserialization/serialization of account data
- Constraint checking (is_signer, is_writable, seeds, etc.)
- Error handling with human-readable messages

**Setup:**
\`\`\`bash
cargo install --git https://github.com/coral-xyz/anchor anchor-cli
anchor init my_program
anchor build && anchor deploy
\`\`\``,
        quiz: [
          {
            question: "What does the #[account(init, payer = user, space = ...)] constraint do?",
            options: [
              "Reads an existing account",
              "Creates a new account, funded by 'user', with specified space",
              "Marks the account as executable",
              "Closes the account and returns rent"
            ],
            correct: 1
          }
        ]
      },
      {
        id: "sol-004",
        title: "SPL Tokens",
        description: "Solana's token standard — mint, transfer, burn",
        xpReward: 180,
        duration: 18,
        chain: "solana",
        tags: ["spl", "tokens", "standards"],
        content: `SPL (Solana Program Library) Token is Solana's equivalent of ERC-20. Every token on Solana — USDC, Bonk, JTO — uses this standard.

**Key accounts:**
- **Mint Account**: Defines the token — total supply, decimals, mint authority, freeze authority
- **Token Account (ATA)**: Holds a user's balance of a specific token. Each wallet has one ATA per token type.
- **Associated Token Account (ATA)**: A deterministic token account address derived from wallet + mint

**Creating a token with Metaplex Token Metadata:**
\`\`\`typescript
import { createUmi } from "@metaplex-foundation/umi-bundle-defaults";
import { createFungible, mplTokenMetadata } from "@metaplex-foundation/mpl-token-metadata";

const umi = createUmi("https://api.devnet.solana.com").use(mplTokenMetadata());

const mint = generateSigner(umi);

await createFungible(umi, {
  name: "My Token",
  symbol: "MTK",
  uri: "https://...", // JSON metadata
  sellerFeeBasisPoints: percentAmount(0),
  decimals: some(9),
}).sendAndConfirm(umi);
\`\`\`

**ATA derivation:**
\`\`\`typescript
import { getAssociatedTokenAddress } from "@solana/spl-token";

const ata = await getAssociatedTokenAddress(
  mintAddress,    // The token's mint
  walletAddress   // The owner's wallet
);
\`\`\`

**Transferring tokens:**
\`\`\`typescript
import { transfer } from "@solana/spl-token";

await transfer(
  connection,
  payer,
  sourceATA,
  destinationATA,
  owner,
  amount * 10 ** decimals
);
\`\`\`

**Compression (cNFTs):**
Solana supports state compression — you can mint millions of tokens/NFTs at near-zero cost using Merkle trees.`,
        quiz: [
          {
            question: "What is an Associated Token Account (ATA)?",
            options: [
              "The mint account for a token",
              "A deterministic token account address derived from a wallet + mint address",
              "A special wallet type",
              "The program that manages all tokens"
            ],
            correct: 1
          }
        ]
      },
      {
        id: "sol-005",
        title: "Cross-Program Invocation",
        description: "Programs calling programs — Solana's composability superpower",
        xpReward: 200,
        duration: 20,
        chain: "solana",
        tags: ["cpi", "composability", "programs"],
        content: `Cross-Program Invocation (CPI) is how Solana programs call each other. It's the foundation of DeFi composability on Solana.

**Basic CPI pattern:**
\`\`\`rust
use anchor_lang::prelude::*;
use anchor_spl::token::{self, Transfer, Token};

pub fn transfer_tokens(ctx: Context<TransferTokens>, amount: u64) -> Result<()> {
    let cpi_accounts = Transfer {
        from: ctx.accounts.from_ata.to_account_info(),
        to: ctx.accounts.to_ata.to_account_info(),
        authority: ctx.accounts.authority.to_account_info(),
    };
    let cpi_program = ctx.accounts.token_program.to_account_info();
    let cpi_ctx = CpiContext::new(cpi_program, cpi_accounts);
    token::transfer(cpi_ctx, amount)?;
    Ok(())
}
\`\`\`

**CPI with PDA signing:**
When your program needs to sign on behalf of a PDA:
\`\`\`rust
let seeds = &[b"vault", user.key().as_ref(), &[bump]];
let signer_seeds = &[&seeds[..]];
let cpi_ctx = CpiContext::new_with_signer(cpi_program, cpi_accounts, signer_seeds);
\`\`\`

**Privilege escalation rules:**
- A program can only sign for its own PDAs
- CPIs have a depth limit of 4
- An invoked program's permissions can never exceed the invoking program's

**Real-world use cases:**
- DEX routers (Jupiter) calling multiple AMM programs in one transaction
- Lending protocols calling token programs to transfer collateral
- NFT marketplaces calling token programs to settle trades

**Reentrancy:**
Unlike Solana, Ethereum has reentrancy as a common vulnerability. Solana's account model makes traditional reentrancy impossible — but you still need to update state before CPIs.`,
        quiz: [
          {
            question: "What is Cross-Program Invocation (CPI)?",
            options: [
              "A way to call external APIs from Solana programs",
              "Solana's consensus mechanism",
              "The ability for one program to call another program's instruction",
              "A token standard"
            ],
            correct: 2
          }
        ]
      }
    ]
  },
  {
    id: "defi-deep",
    title: "DeFi Deep Dive",
    description: "AMMs, lending, yield farming — how money legos work",
    chain: "both",
    level: "intermediate",
    totalXP: 2000,
    color: "from-yellow-500 to-orange-600",
    icon: "◈",
    lessons: [
      {
        id: "defi-001",
        title: "How AMMs Work",
        description: "Uniswap's x*y=k formula and why it's genius",
        xpReward: 200,
        duration: 15,
        chain: "both",
        tags: ["amm", "uniswap", "defi", "liquidity"],
        content: `Automated Market Makers (AMMs) replaced traditional order books with a mathematical formula. Uniswap's constant product formula changed DeFi forever.

**The x*y=k invariant:**
\`\`\`
x = reserve of token A
y = reserve of token B  
k = x * y (constant)

When you trade token A for token B:
new_x = x + dx
new_y = k / new_x
dy = y - new_y  (you receive dy token B)
\`\`\`

**Slippage:**
The price impact of your trade. Large trades relative to pool size = high slippage.
\`\`\`
price_impact = dx / (x + dx)
\`\`\`

**Liquidity Providers (LPs):**
- Deposit equal value of both tokens
- Receive LP tokens representing their pool share
- Earn trading fees (0.3% on Uniswap v2) proportional to share
- Risk: Impermanent Loss

**Impermanent Loss:**
When the price ratio of your deposited tokens changes, you'd have been better off just holding. IL = 2√P/(1+P) - 1 where P = price ratio change.

Example: If ETH doubles in price after you LP, you lose ~5.7% vs simply holding.

**Uniswap V3 innovations:**
- Concentrated liquidity — LPs choose price ranges
- Capital efficiency up to 4000x
- Multiple fee tiers (0.01%, 0.05%, 0.3%, 1%)

**Key contracts:**
\`\`\`solidity
// Swapping via Uniswap V3 Router
ISwapRouter.ExactInputSingleParams memory params = ISwapRouter.ExactInputSingleParams({
    tokenIn: WETH,
    tokenOut: USDC,
    fee: 3000,
    recipient: msg.sender,
    deadline: block.timestamp + 60,
    amountIn: 1 ether,
    amountOutMinimum: minOut, // slippage protection
    sqrtPriceLimitX96: 0
});
uint256 amountOut = router.exactInputSingle(params);
\`\`\``,
        quiz: [
          {
            question: "In x*y=k, what does k represent?",
            options: [
              "The token price",
              "The total liquidity",
              "A constant product that must be maintained after every swap",
              "The fee rate"
            ],
            correct: 2
          }
        ]
      },
      {
        id: "defi-002",
        title: "Flash Loans",
        description: "Borrow unlimited capital with zero collateral in one transaction",
        xpReward: 250,
        duration: 18,
        chain: "both",
        tags: ["flash loans", "aave", "defi", "arbitrage"],
        content: `Flash loans are uncollateralized loans that must be borrowed and repaid in the same transaction. They're only possible because of blockchain atomicity.

**How they work:**
1. Borrow any amount from the pool
2. Do anything with it (arbitrage, liquidations, collateral swaps)
3. Repay the loan + fee in the same transaction
4. If repayment fails → entire transaction reverts

**Aave flash loan:**
\`\`\`solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@aave/core-v3/contracts/flashloan/base/FlashLoanSimpleReceiverBase.sol";

contract FlashLoanArbitrage is FlashLoanSimpleReceiverBase {
    constructor(IPoolAddressesProvider provider)
        FlashLoanSimpleReceiverBase(provider) {}

    function executeOperation(
        address asset,
        uint256 amount,
        uint256 premium,     // 0.05% fee
        address initiator,
        bytes calldata params
    ) external override returns (bool) {
        // YOUR LOGIC HERE
        // e.g., buy low on DEX A, sell high on DEX B

        // Must approve repayment
        uint256 amountOwed = amount + premium;
        IERC20(asset).approve(address(POOL), amountOwed);
        return true;
    }

    function executeFlashLoan(address asset, uint256 amount) external {
        POOL.flashLoanSimple(address(this), asset, amount, bytes(""), 0);
    }
}
\`\`\`

**Use cases:**
- Arbitrage between DEXes
- Collateral swaps (change your Aave collateral without unwinding position)
- Self-liquidation (avoid liquidation penalty)
- One-step leverage

**Attack history:**
Flash loans enabled some of the largest DeFi exploits — the 2020 bZx attacks (~$1M), the Euler Finance hack ($197M), and many oracle manipulation attacks.`,
        quiz: [
          {
            question: "What happens if you can't repay a flash loan?",
            options: [
              "You pay a penalty fee",
              "The entire transaction reverts — no money moves at all",
              "Your collateral is liquidated",
              "You have 24 hours to repay"
            ],
            correct: 1
          }
        ]
      }
    ]
  },
  {
    id: "web3-security",
    title: "Web3 Security",
    description: "Find bugs, think like an attacker, protect protocols",
    chain: "both",
    level: "advanced",
    totalXP: 2500,
    color: "from-red-500 to-pink-600",
    icon: "🛡",
    lessons: [
      {
        id: "sec-001",
        title: "Reentrancy Attacks",
        description: "The bug that killed The DAO — and how to prevent it",
        xpReward: 300,
        duration: 20,
        chain: "ethereum",
        tags: ["reentrancy", "security", "attacks"],
        content: `Reentrancy is one of the most infamous smart contract vulnerabilities. It was exploited in the DAO hack of 2016, draining 3.6 million ETH (~$60M at the time) and causing the Ethereum hard fork.

**Vulnerable contract:**
\`\`\`solidity
contract VulnerableBank {
    mapping(address => uint) public balances;

    function deposit() external payable {
        balances[msg.sender] += msg.value;
    }

    function withdraw() external {
        uint amount = balances[msg.sender];
        require(amount > 0, "Nothing to withdraw");

        // VULNERABLE: sends ETH before updating state
        (bool success, ) = msg.sender.call{value: amount}("");
        require(success, "Transfer failed");

        balances[msg.sender] = 0; // Too late!
    }
}
\`\`\`

**Attacker contract:**
\`\`\`solidity
contract Attacker {
    VulnerableBank victim;

    constructor(address _victim) {
        victim = VulnerableBank(_victim);
    }

    function attack() external payable {
        victim.deposit{value: msg.value}();
        victim.withdraw();
    }

    // Called when ETH is received
    receive() external payable {
        if (address(victim).balance >= msg.value) {
            victim.withdraw(); // Reenter before balance is set to 0!
        }
    }
}
\`\`\`

**The fix — Checks-Effects-Interactions pattern:**
\`\`\`solidity
function withdraw() external {
    uint amount = balances[msg.sender];
    require(amount > 0, "Nothing to withdraw");

    balances[msg.sender] = 0; // 1. EFFECTS first
    
    (bool success, ) = msg.sender.call{value: amount}(""); // 2. INTERACTIONS last
    require(success, "Transfer failed");
}
\`\`\`

**Or use a reentrancy guard:**
\`\`\`solidity
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";

contract SafeBank is ReentrancyGuard {
    function withdraw() external nonReentrant {
        // nonReentrant modifier prevents reentrancy
    }
}
\`\`\`

**Read-only reentrancy:**
Even view functions can be exploited if other contracts read your state during a callback. Balancer v1 was exploited this way.`,
        quiz: [
          {
            question: "What is the Checks-Effects-Interactions pattern?",
            options: [
              "Check permissions, then interact with external contracts, then update state",
              "Validate inputs, update state, then interact with external contracts",
              "Check balances, run effects, call interfaces",
              "A Solidity code style guide"
            ],
            correct: 1
          }
        ]
      }
    ]
  }
];

export function getPathById(id: string): LearningPath | undefined {
  return LEARNING_PATHS.find(p => p.id === id);
}

export function getLessonById(lessonId: string): { lesson: Lesson; path: LearningPath } | undefined {
  for (const path of LEARNING_PATHS) {
    const lesson = path.lessons.find(l => l.id === lessonId);
    if (lesson) return { lesson, path };
  }
  return undefined;
}
