import type {
  FormalReport,
  InvariantRegistry,
  FindingRegistry,
  HypothesisRegistry,
  EconomicAnalysis,
  CrossContractAnalysis,
  RemediationPlan,
  VerificationPlan,
  ArchitectureSummary,
  IntentSummary,
  WorkspaceAnalysis
} from "@srp/shared-types";
import { PHASE_LABELS } from "@srp/methodology";

/**
 * All artifacts needed to compile a complete report.
 */
export interface ReportCompilationInput {
  readonly workspace: WorkspaceAnalysis;
  readonly intent: IntentSummary;
  readonly architecture?: ArchitectureSummary;
  readonly invariants?: InvariantRegistry;
  readonly verificationPlan?: VerificationPlan;
  readonly hypotheses?: HypothesisRegistry;
  readonly economicAnalysis?: EconomicAnalysis;
  readonly crossContractAnalysis?: CrossContractAnalysis;
  readonly findingRegistry?: FindingRegistry;
  readonly remediationPlan?: RemediationPlan;
}

/**
 * Report section used during compilation.
 */
export interface ReportSection {
  readonly heading: string;
  readonly level: number;
  readonly content: string;
}

/**
 * Compiles a formal audit report from accumulated audit artifacts.
 */
export function compileReport(
  input: ReportCompilationInput,
  modelName: string = "report-engine"
): FormalReport {
  const timestamp = new Date().toISOString();
  const sections: ReportSection[] = [];

  sections.push({
    heading: "Executive Summary",
    level: 2,
    content: buildExecutiveSummary(input)
  });

  if (input.architecture) {
    sections.push({
      heading: "Architecture Overview",
      level: 2,
      content: input.architecture.markdownSummary
    });
  }

  if (input.invariants && input.invariants.invariants.length > 0) {
    sections.push({
      heading: "Security Invariants",
      level: 2,
      content: formatInvariantsSection(input.invariants)
    });
  }

  if (input.verificationPlan && input.verificationPlan.items.length > 0) {
    sections.push({
      heading: "Verification Plan",
      level: 2,
      content: formatVerificationSection(input.verificationPlan)
    });
  }

  if (input.hypotheses && input.hypotheses.hypotheses.length > 0) {
    sections.push({
      heading: "Attack Hypotheses",
      level: 2,
      content: formatHypothesesSection(input.hypotheses)
    });
  }

  if (input.economicAnalysis && input.economicAnalysis.risks.length > 0) {
    sections.push({
      heading: "Economic & Systemic Risks",
      level: 2,
      content: formatEconomicSection(input.economicAnalysis)
    });
  }

  if (input.crossContractAnalysis && input.crossContractAnalysis.paths.length > 0) {
    sections.push({
      heading: "Cross-Contract Paths",
      level: 2,
      content: formatCrossContractSection(input.crossContractAnalysis)
    });
  }

  if (input.findingRegistry && input.findingRegistry.findings.length > 0) {
    sections.push({
      heading: "Security Findings",
      level: 2,
      content: formatFindingsSection(input.findingRegistry)
    });
  }

  if (input.remediationPlan && input.remediationPlan.actions.length > 0) {
    sections.push({
      heading: "Remediation Roadmap",
      level: 2,
      content: formatRemediationSection(input.remediationPlan)
    });
  }

  const title = `Security Audit Report: ${input.intent.mainContracts.join(", ") || "Protocol"}`;

  const markdownContent = [
    `# ${title}`,
    "",
    `**Generated At:** ${timestamp}`,
    `**Model:** ${modelName}`,
    `**Workspace:** \`${input.workspace.rootDirectory}\``,
    "",
    "---",
    "",
    ...sections.map((s) => `${"#".repeat(s.level)} ${s.heading}\n\n${s.content}\n`),
    "---",
    "*Report generated by Security Reasoning Protocol (SRP) Report Engine.*"
  ].join("\n");

  return {
    id: `REP-${Date.now()}`,
    title,
    markdownContent,
    generatedAt: timestamp,
    generatedByModel: modelName
  };
}

function buildExecutiveSummary(input: ReportCompilationInput): string {
  const findingsCount = input.findingRegistry?.findings.length ?? 0;
  const criticalCount = input.findingRegistry?.findings.filter((f) => f.severity === "Critical").length ?? 0;
  const highCount = input.findingRegistry?.findings.filter((f) => f.severity === "High").length ?? 0;

  return [
    `This report presents the findings of an automated security audit of the protocol codebase at \`${input.workspace.rootDirectory}\`.`,
    "",
    `**Files Analyzed:** ${input.workspace.solidityFileCount}`,
    `**Invariants Extracted:** ${input.invariants?.invariants.length ?? 0}`,
    `**Hypotheses Formulated:** ${input.hypotheses?.hypotheses.length ?? 0}`,
    `**Findings Verified:** ${findingsCount} (${criticalCount} Critical, ${highCount} High)`,
    `**Remediation Actions:** ${input.remediationPlan?.actions.length ?? 0}`
  ].join("\n");
}

function formatInvariantsSection(registry: InvariantRegistry): string {
  return registry.invariants
    .map((inv) => `### ${inv.id}: ${inv.title}\n- **Category:** ${inv.category}\n- **Priority:** ${inv.priority}\n- ${inv.description}`)
    .join("\n\n");
}

function formatVerificationSection(plan: VerificationPlan): string {
  return plan.items
    .map((item) => `### ${item.id}: ${item.title}\n- **Type:** ${item.verificationType}\n- **Tool:** ${item.recommendedTool}\n- ${item.description}`)
    .join("\n\n");
}

function formatHypothesesSection(registry: HypothesisRegistry): string {
  return registry.hypotheses
    .map((hyp) => `### ${hyp.id}: ${hyp.title}\n- **Likelihood:** ${hyp.likelihood}\n- **Surface:** ${hyp.attackSurface}\n- ${hyp.description}`)
    .join("\n\n");
}

function formatEconomicSection(analysis: EconomicAnalysis): string {
  return analysis.risks
    .map((risk) => `### ${risk.id}: ${risk.title}\n- **Severity:** ${risk.severity}\n- **Impact:** ${risk.impact}\n- **Mitigation:** ${risk.mitigationStrategy}`)
    .join("\n\n");
}

function formatCrossContractSection(analysis: CrossContractAnalysis): string {
  return analysis.paths
    .map((path) => `### ${path.id}: ${path.title}\n- **Flow:** ${path.steps.map((s) => `${s.contract}.${s.method}`).join(" → ")}\n- **Critical Points:** ${path.criticalPoints.join(", ")}`)
    .join("\n\n");
}

function formatFindingsSection(registry: FindingRegistry): string {
  return registry.findings
    .map((f) => `### ${f.id}: ${f.title}\n- **Severity:** ${f.severity}\n- **Status:** ${f.status}\n- **Target:** ${f.targetComponent}\n- ${f.description}\n- **Mitigation:** ${f.mitigation ?? "N/A"}`)
    .join("\n\n");
}

function formatRemediationSection(plan: RemediationPlan): string {
  return plan.actions
    .map((action) => `### ${action.id}: ${action.title}\n- **Finding:** ${action.relatedFindingId}\n- **Complexity:** ${action.complexity}\n- **Effort:** ${action.estimatedEffort}\n- ${action.description}`)
    .join("\n\n");
}

/**
 * Counts findings by severity.
 */
export function findingSeverityCounts(registry: FindingRegistry): Readonly<Record<string, number>> {
  const counts: Record<string, number> = {};
  for (const finding of registry.findings) {
    counts[finding.severity] = (counts[finding.severity] ?? 0) + 1;
  }
  return counts;
}
